version: '3.8'

services:
  deeplx:
    image: ghcr.io/owo-network/deeplx:latest
    restart: always
    ports:
      - "1188:1188"
    # environment:
      # - TOKEN=helloworld
      # - DL_SESSION=xxxxxx